name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    # Note: we use `pull_request` instead of `pull_request_target` to avoid
    # running with elevated privileges on code from forks.
    types: [opened]
    branches: [main]

permissions: {}
# NOTE: Default token permissions are disabled; jobs must explicitly set the minimal permissions they need.

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      # Note: PR greetings are posted via the Issues API; `pull-requests: read` is only used
      # to check whether a user has opened a PR before.
      issues: write
      pull-requests: read
    steps:
      - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1.3.0 (v1) https://github.com/actions/first-interaction/releases
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: "Message that will be displayed on users' first issue"
          pr_message: "Message that will be displayed on users' first pull request"
